# Generated by Django 4.2.6 on 2023-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('number', models.TextField()),
            ],
        ),
    ]
